mutation CreateModule($title: String!, $description: String!, $difficultyLevel: String!) @auth(level: USER) {
  module_insert(data: { title: $title, description: $description, difficultyLevel: $difficultyLevel, createdAt_expr: "request.time" })
}

query ListModules @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  modules {
    id
    title
    description
    difficultyLevel
  }
}

mutation EnrollStudent($studentId: UUID!, $moduleId: UUID!) @auth(level: USER) {
  enrollment_insert(data: { studentId: $studentId, moduleId: $moduleId, enrollmentDate_expr: "request.time", status: "Enrolled" })
}

query GetUser(@auth(level: USER) {
  user(key: {id_expr: "auth.uid"}) {
    id
    username
    email
    role
  }
}